-- SELECT DISTINCT(SALE_DATE)
-- FROM SALES;




-- SELECT DISTINCT
-- (DATE_FORMAT(SALE_DATE,'%a %D %b %Y')) AS 'DATE'
-- FROM SALES;




-- SELECT CURRENT_DATE() 
-- AS 'CURRENT-DATE', 
-- CURRENT_TIME() AS 'CURRENT_TIME';


-- SELECT DAYOFMONTH(EMP_DOB) AS 'DAY',
-- MONTH(EMP_DOB) AS 'MONTH',
-- YEAR(EMP_DOB) AS 'YEAR'
-- FROM EMPLOYEE
-- WHERE MONTH(EMP_DOB) = '11';

-- SELECT EMP_FNAME,EMP_LNAME,EMP_DOB,
-- DATE_FORMAT(EMP_DOB,'%b') AS MONTH
-- FROM EMPLOYEE
-- WHERE MONTH(EMP_DOB) = '11';




-- SELECT EMP_LNAME,EMP_FNAME,EMP_HIRE_DATE,
-- ADDDATE(EMP_HIRE_DATE, INTERVAL 12 MONTH) AS "FIRST APPRAISAL"
-- FROM EMPLOYEE;



-- SELECT * 
-- FROM SALES
-- WHERE SALE_DATE >= LAST_DAY(SALE_DATE)-20;



-- SELECT LINE_PRICE,ROUND(LINE_PRICE,1) AS 'LINE_PRICE1',
-- ROUND(LINE_PRICE,0) AS 'LINEPRICE2',
-- TRUNCATE(LINE_PRICE,0) AS 'TRUNCATED VALUE'
-- FROM SALES_LINE
-- WHERE LINE_QTY > 2;

-- SELECT TRANSACTION_NO,LINE_PRICE,MOD(LINE_PRICE,10)
-- FROM SALES_LINE
-- WHERE LINE_QTY > 2;


-- SELECT CONCAT(EMP_LNAME,EMP_FNAME) AS NAME
-- FROM EMPLOYEE;

-- SELECT CONCAT(UPPER(EMP_LNAME),' ',LOWER(EMP_FNAME)) AS NAME
-- FROM EMPLOYEE;


-- SELECT EMP_PHONE,SUBSTR(EMP_FNAME,1,3)
-- FROM EMPLOYEE;

-- SELECT EMP_FNAME,EMP_LNAME, 
-- CONCAT(DATE_FORMAT(EMP_DOB,'%d'),UPPER(SUBSTR(EMP_LNAME,1,6))) AS "USER_ID"
-- FROM EMPLOYEE;




-- SELECT ATTRACT_NAME,LENGTH(ATTRACT_NAME) AS NAMESIZE
-- FROM ATTRACTION
-- ORDER BY NAMESIZE DESC;




-- SELECT 10 + '10';

-- SELECT 10, CAST(10 AS CHAR);





