SELECT EMP_LNAME,EMP_FNAME,EMP_DOB
FROM EMPLOYEE
WHERE DATE_FORMAT(EMP_DOB,'%d') = 14;


SELECT AVG(DATE_FORMAT('2008-11-25','%Y') - YEAR(EMP_DOB)) 
AS APPROXIMATE_AGE
FROM EMPLOYEE;

SELECT EMP_FNAME,EMP_LNAME,
CONCAT(SUBSTR(EMP_PHONE,1,3),LOWER(SUBSTR(EMP_FNAME,1,2))) AS USER_PASSWORD
FROM EMPLOYEE;

SELECT DISTINCT(DATE_FORMAT(SALE_DATE,'%a-%d-%m-%y')) AS DATE
FROM SALES