DROP VIEW EMP_DETAILS;
CREATE VIEW EMP_DETAILS AS
SELECT EMP_NUM, EMPLOYEE.PARK_CODE,PARK_NAME, EMP_LNAME, EMP_FNAME, EMP_HIRE_DATE,EMP_DOB
FROM EMPLOYEE, THEMEPARK
WHERE THEMEPARK.PARK_CODE = EMPLOYEE.PARK_CODE;

SELECT EMP_FNAME, EMP_LNAME, THEMEPARK.PARK_NAME
FROM EMPLOYEE,THEMEPARK
WHERE EMPLOYEE.PARK_CODE = THEMEPARK.PARK_CODE;

grant select,show view on 'themepark' to 'zamm'@'localhost' identified by '123
4';

GRANT SELECT ON 
themepark.THEMEPARK
TO 'asad'@'localhost';

GRANT CREATE 
ON themepark.*
TO 'asad'@'localhost';

CREATE VIEW SALES_DETAILS AS  
SELECT TRANSACTION_NO,LINE_NO
FROM SALES_LINE;

