/***********************Arthimatic-Operations*************************************/

SELECT PARK_CODE, TICKET_NO,
TICKET_TYPE, TICKET_PRICE, 
TICKET_PRICE + ROUND((TICKET_PRICE*0.1),2) FROM TICKET;


SELECT PARK_CODE, TICKET_NO,
TICKET_TYPE, TICKET_PRICE, 
TICKET_PRICE + ROUND((TICKET_PRICE*0.1),2)PRICE_INCREASED FROM TICKET;

SELECT PARK_CODE, TICKET_NO,
TICKET_TYPE, TICKET_PRICE, 
TICKET_PRICE + ROUND((TICKET_PRICE*0.1),2) AS 'PRICE INCREASED' FROM TICKET;




/***********GREATER THAN**************/
SELECT PARK_CODE, TICKET_TYPE, TICKET_PRICE
FROM TICKET
WHERE TICKET_PRICE > 20;

/***********LESS THAN**************/
SELECT PARK_CODE, TICKET_TYPE, TICKET_PRICE
FROM TICKET
WHERE TICKET_PRICE < 30;

/******************CHARACTER COMPARISONS***********************/
SELECT PARK_CODE, PARK_NAME, PARK_COUNTRY
FROM THEMEPARK
WHERE PARK_CODE < 'UK2262';


/*****************BETWEEN**************************/
SELECT *
FROM TICKET
WHERE TICKET_PRICE BETWEEN 30.00 AND 50.00;

SELECT * 
FROM HOURS
WHERE HOURS_PER_ATTRACT BETWEEN 5 AND 10;

/*********************IN OPERATOR*********************/
SELECT *
FROM SALES_LINE 
WHERE TRANSACTION_NO IN (12781,67593);

SELECT *
FROM TICKET
WHERE TICKET_TYPE IN ('Child','Senior');

/******************LIKE OPERATOR*************************/
SELECT EMP_LNAME, EMP_FNAME, EMP_NUM
FROM EMPLOYEE 

WHERE EMP_FNAME LIKE "A%";

SELECT EMP_LNAME, EMP_FNAME, EMP_NUM
FROM EMPLOYEE 
WHERE EMP_FNAME LIKE 'A_f';

SELECT * 
FROM THEMEPARK
WHERE PARK_NAME LIKE "%Land"; /* '%' in start means end & in end means starts with that particular char or string

/*************************NULL & IS NULL**********************************/
SELECT *
FROM ATTRACTION
WHERE ATTRACT_NAME is NULL;

/*******************LOGICAL Operators****************************************/
/*********************AND*************************/
SELECT EMP_NUM, ATTRACT_NO
FROM HOURS
WHERE HOURS_PER_ATTRACT > 3
AND DATE_WORKED > '18-MAY-2007';

SELECT * 
FROM ATTRACTION
WHERE ATTRACT_AGE <= 10 AND ATTRACT_CAPACITY < 100 AND ATTRACT_NAME IS NOT NULL;

/**************OR-OPERATOR*********************************/

SELECT PARK_NAME, PARK_COUNTRY
FROM THEMEPARK
WHERE PARK_COUNTRY = "FR" 
OR PARK_COUNTRY = "UK";

SELECT * 
FROM ATTRACTION
WHERE (PARK_CODE LIKE 'FR%'
AND ATTRACT_CAPACITY < 50) 
OR (ATTRACT_CAPACITY > 100);

/************NOT_OPERATOR********************/
SELECT * 
FROM EMPLOYEE 
WHERE NOT(EMP_NUM = 106) 
AND NOT(EMP_TITLE = 'Ms');

/*********************EXCERCISE****************************/
                      /**4.1**/
SELECT *
FROM THEMEPARK
WHERE NOT(PARK_COUNTRY='UK'); 

            /**4.2**/
SELECT *
FROM SALES
WHERE SALE_DATE = '2007-05-18';

        /**4.3**/
SELECT *
FROM TICKET
WHERE TICKET_PRICE BETWEEN 20 AND 30;

        /**4.4**/
SELECT *
FROM ATTRACTION
WHERE ATTRACT_CAPACITY > 60;

        /**4.5**/
SELECT ATTRACT_NO,
    HOUR_RATE, HOUR_RATE + ROUND((HOUR_RATE*0.2),2) 
    AS "INCREASED HOURLY RATE" 
    FROM HOURS;



