--------------------------------------------------------------------------------------
-- NAME	       : OT (ORACLE TUTORIAL) SAMPLE DATABASE
-- LINK	       : HTTP://WWW.ORACLETUTORIAL.COM/ORACLE-SAMPLE-DATABASE/
-- VERSION     : 1.0
-- LAST UPDATED: JULY-28-2017
-- COPYRIGHT   : COPYRIGHT � 2017 BY WWW.ORACLETUTORIAL.COM. ALL RIGHTS RESERVED.
-- NOTICE      : USE THIS SAMPLE DATABASE FOR THE EDUCATIONAL PURPOSE ONLY.
--               CREDIT THE SITE ORACLETUTORIAL.COM EXPLITLY IN YOUR MATERIALS THAT
--               USE THIS SAMPLE DATABASE.
--------------------------------------------------------------------------------------
DROP TABLE ORDER_ITEMS;  
DROP TABLE ORDERS;
DROP TABLE INVENTORIES;
DROP TABLE PRODUCTS;
DROP TABLE PRODUCT_CATEGORIES;
DROP TABLE WAREHOUSES;
DROP TABLE EMPLOYEES;
DROP TABLE CONTACTS;
DROP TABLE CUSTOMERS;
DROP TABLE LOCATIONS;
DROP TABLE COUNTRIES;
DROP TABLE REGIONS;